### ISSUE TITLE
TODO: Implement search functionality

### ISSUE THREAD

**Issue by theonlyasdk** [theonlyasdk/ormali#1]
Add functionality to the search field, and make it filter saved notes by the search term

**Comment by Mohit-3007** [comment]
Hi @theonlyasdk 

I am interested in doing this, Kindly assign the same to me

**Comment by theonlyasdk** [comment]
Hey! Thank you for contributing! You can try adding the function to tasks.js or create a new file for it (don't forget to import it in index.htm)
